From 54622953c4cc09196c7f16d8229ba438afbe626f Mon Sep 17 00:00:00 2001
From: Brian Waldon <bcwaldon@gmail.com>
Date: Sun, 22 Apr 2012 22:21:53 -0700
Subject: [PATCH] Fix i18n in glance.notifier.notify_kombu

* Fixes bug 983829

Change-Id: Ibc5ec12e97e69797d1952c020c3091f42480abec
---
 glance/notifier/notify_kombu.py |    5 +++--
 1 files changed, 3 insertions(+), 2 deletions(-)

diff --git a/glance/notifier/notify_kombu.py b/glance/notifier/notify_kombu.py
index b3447d6..6623fdc 100644
--- a/glance/notifier/notify_kombu.py
+++ b/glance/notifier/notify_kombu.py
@@ -166,8 +166,9 @@ class RabbitStrategy(strategy.Strategy):
 
     def log_failure(self, msg, priority):
         """Fallback to logging when we can't send to rabbit."""
-        logger.error(_('Notification with priority %(priority)s failed; '
-                'msg=%s') % msg)
+        message = _('Notification with priority %(priority)s failed: '
+                    'msg=%(msg)s')
+        logger.error(message % {'msg': msg, 'priority': priority})
 
     def _send_message(self, msg, routing_key):
         """Send a message.  Caller needs to catch exceptions for retry."""
